language: elixir
elixir:
  - 1.0.2
otp_release:
  - 17.4
sudo: false
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - joel@vorce.se

